// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcFM4KOqeNrVsDUXpoLsJKJIY5XJqj7Ek',
    appId: '1:613157869257:web:f77c4b794a191549c65f18',
    messagingSenderId: '613157869257',
    projectId: 'straydogapp-76ffa',
    authDomain: 'straydogapp-76ffa.firebaseapp.com',
    storageBucket: 'straydogapp-76ffa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf6rKiBgXJw0KM2zHJM53dJDuQHccZC2o',
    appId: '1:613157869257:android:f80cb096f9b33bb8c65f18',
    messagingSenderId: '613157869257',
    projectId: 'straydogapp-76ffa',
    storageBucket: 'straydogapp-76ffa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4wLfT04qsgxJ-1ETcbNXM2BJohu1I1vg',
    appId: '1:613157869257:ios:29ba274bb1a1187cc65f18',
    messagingSenderId: '613157869257',
    projectId: 'straydogapp-76ffa',
    storageBucket: 'straydogapp-76ffa.appspot.com',
    iosBundleId: 'com.example.strayDogApp',
  );
}
